# Generated by Django 3.1.5 on 2021-01-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210113_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='heat',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Seafood', 'Seafood'), ('Vegetable', 'Vegetable'), ('Misc', 'Misc')], max_length=20),
        ),
    ]
