# Generated by Django 3.1.5 on 2021-01-13 23:33

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210113_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Misc', 'Misc'), ('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Seafood', 'Seafood'), ('Vegetable', 'Vegetable')], default='Misc', max_length=20),
        ),
    ]
