# Generated by Django 3.1.5 on 2021-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210113_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color1',
            field=models.CharField(default='100,100,100', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='color2',
            field=models.CharField(default='100,100,100', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='color3',
            field=models.CharField(default='100,100,100', max_length=100),
        ),
    ]
