# Generated by Django 3.1.5 on 2021-01-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210125_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='color3',
        ),
    ]
