# Generated by Django 3.1.5 on 2021-02-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210125_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color0',
            field=models.CharField(default='100,100,100', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='color1',
            field=models.CharField(default='100,100,100', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='color2',
            field=models.CharField(default='100,100,100', max_length=100),
        ),
    ]
